case_name: "IRL-four_straight_gate"
nn_type: "gatenet"
bound_method: "backward"
render_method: "splatfacto"
odd_type: "cuboid"
run_datetime: "20260223_221554"

width: 32
height: 32

debug: True
threshold: [850.0, 530.0, 570.0]
show_details: False
