bound_method: "forward"
render_method: "splatfacto"
case_name: "boeing_airplane"
odd_type: "cylinder"
save_filename: null
debug: true

width: 256
height: 256
fx: 216
fy: 216
eps2d: 8.0

downsampling_ratio: 2
tile_size_abstract: 2
tile_size_render: 24
min_distance: 0.01
max_distance: 100.0
gs_batch: 200
part: [10, 20, 20]

data_time: "2026-01-31_235019"
checkpoint_filename: "step-000299999.ckpt"

bg_img_path: null
bg_pure_color: [0.0, 1.0, 0.0]

save_ref: true
save_bound: true
N_samples: 5
